apiVersion: v1
kind: Secret
metadata:
  name: appsecrets
data:
  user: {{ .Values.user | quote }}
  name: {{ .Values.name | quote }}
  password: {{ .Values.password | quote }}
  host: {{ .Values.host | quote }}
  port: {{ .Values.port | quote }}
